CREATE CACHED TABLE "SYS_ORG"
(
    "ID"          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    "CREATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT U&'\521b\5efa\65f6\95f4',
    "UPDATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT U&'\4fee\6539\65f6\95f4',
    "ADDRESS"     CHARACTER VARYING(255),
    "CITY"        CHARACTER VARYING(32),
    "CONTACTS"    CHARACTER VARYING(64),
    "COUNTY"      CHARACTER VARYING(32),
    "EMAIL"       CHARACTER VARYING(128),
    "MEMO"        CHARACTER VARYING(255),
    "MOBILE_NO"   CHARACTER VARYING(20),
    "NAME"        CHARACTER VARYING(64),
    "PARENT_ID"   BIGINT                                                 NOT NULL,
    "PROVINCE"    CHARACTER VARYING(32),
    "STATUS"      CHARACTER VARYING(16),
    "TELEPHONE"   CHARACTER VARYING(20)
);

ALTER TABLE "SYS_ORG"
    ADD CONSTRAINT "CONSTRAINT_C" PRIMARY KEY ("ID");

-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SYS_ORG;
CREATE CACHED TABLE "SYS_PORTALLET"
(
    "ID"          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    "CREATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT U&'\521b\5efa\65f6\95f4',
    "UPDATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT U&'\4fee\6539\65f6\95f4',
    "COLLAPSIBLE" INTEGER                                                NOT NULL,
    "CONTENT"     CHARACTER VARYING(255),
    "HEIGHT"      INTEGER                                                NOT NULL,
    "HREF"        CHARACTER VARYING(128),
    "LOAD_MODE"   INTEGER                                                NOT NULL,
    "SHOW_MODE"   INTEGER                                                NOT NULL,
    "TITLE"       CHARACTER VARYING(64)                                  NOT NULL,
    "USER_NAME"   CHARACTER VARYING(32),
    "WIDTH"       INTEGER                                                NOT NULL
);
ALTER TABLE "SYS_PORTALLET"
    ADD CONSTRAINT "CONSTRAINT_D" PRIMARY KEY ("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SYS_PORTALLET;
CREATE CACHED TABLE "SYS_RESOURCE"
(
    "ID"          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    "CREATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT U&'\521b\5efa\65f6\95f4',
    "UPDATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT U&'\4fee\6539\65f6\95f4',
    "DESCN"       CHARACTER VARYING(255),
    "ICON"        CHARACTER VARYING(64),
    "NAME"        CHARACTER VARYING(64)                                  NOT NULL,
    "ORDER_TIME"  TIMESTAMP                                              NOT NULL,
    "SHOW_MODE"   INTEGER                                                NOT NULL,
    "SHOW_STATE"  INTEGER                                                NOT NULL,
    "TYPE"        CHARACTER VARYING(16)                                  NOT NULL,
    "VALUE"       CHARACTER VARYING(255),
    "PARENTID"    BIGINT
);
ALTER TABLE "SYS_RESOURCE"
    ADD CONSTRAINT "CONSTRAINT_9" PRIMARY KEY ("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SYS_RESOURCE;
CREATE CACHED TABLE "SYS_ROLE"
(
    "ID"          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    "CREATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT U&'\521b\5efa\65f6\95f4',
    "UPDATE_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT U&'\4fee\6539\65f6\95f4',
    "DESCN"       CHARACTER VARYING(255)                                 NOT NULL,
    "NAME"        CHARACTER VARYING(64)                                  NOT NULL,
    "ORG_ID"      BIGINT
);
ALTER TABLE "SYS_ROLE"
    ADD CONSTRAINT "CONSTRAINT_A" PRIMARY KEY ("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SYS_ROLE;
CREATE CACHED TABLE "SYS_ROLE_RESC"
(
    "ROLE_ID" BIGINT NOT NULL,
    "RESC_ID" BIGINT NOT NULL
);
ALTER TABLE "SYS_ROLE_RESC"
    ADD CONSTRAINT "CONSTRAINT_AA" PRIMARY KEY ("ROLE_ID", "RESC_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SYS_ROLE_RESC;
CREATE CACHED TABLE "SYS_USER"
(
    "ID"               BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    "CREATE_TIME"      TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT U&'\521b\5efa\65f6\95f4',
    "UPDATE_TIME"      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT U&'\4fee\6539\65f6\95f4',
    "DESCN"            CHARACTER VARYING(255),
    "EMAIL"            CHARACTER VARYING(128)                                 NOT NULL,
    "EXPIRATION_TIME"  TIMESTAMP,
    "LAST_MODIFY_TIME" TIMESTAMP,
    "LOGIN_FAIL_TIMES" INTEGER,
    "LOGIN_STATUS"     INTEGER,
    "LOGIN_TIME"       TIMESTAMP,
    "MOBILE_NO"        CHARACTER VARYING(32),
    "ORG_ID"           BIGINT,
    "ORG_NAME"         CHARACTER VARYING(64),
    "PASSWORD"         CHARACTER VARYING(255)                                 NOT NULL,
    "PINYIN"           CHARACTER VARYING(32),
    "REAL_NAME"        CHARACTER VARYING(32),
    "SALT"             CHARACTER VARYING(64)                                  NOT NULL,
    "STATUS"           INTEGER,
    "UNLOCK_TIME"      TIMESTAMP,
    "USER_TYPE"        INTEGER                                                NOT NULL,
    "USERNAME"         CHARACTER VARYING(32)                                  NOT NULL
);
ALTER TABLE "SYS_USER"
    ADD CONSTRAINT "CONSTRAINT_A5" PRIMARY KEY ("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SYS_USER;
CREATE CACHED TABLE "SYS_USER_ROLE"
(
    "USER_ID" BIGINT NOT NULL,
    "ROLE_ID" BIGINT NOT NULL
);
ALTER TABLE "SYS_USER_ROLE"
    ADD CONSTRAINT "CONSTRAINT_AAB" PRIMARY KEY ("USER_ID", "ROLE_ID");


INSERT INTO sys_org (id, parent_id, name, status, province, city, county, mobile_no, address, contacts, telephone, email, create_time, update_time, memo)
VALUES (1, 0, 'acooly', 'valid', '重庆市', '重庆市', '渝北区', '13896177630', '重庆渝北', '张浦', '', 'zhangpu@acooly.cn', '2019-02-21 18:05:36', '2019-02-21 18:05:36', 'dev');

insert into sys_resource (id, name, type, show_state, show_mode, order_time, icon)
values (1, '系统管理', 'MENU', 0, 1, '2014-01-07', 'fa-cogs');
insert into sys_resource (id, parentid, name, type, "VALUE", show_state, show_mode, order_time, icon, descn)
values (2, 1, '账户管理', 'URL', '/manage/system/user/index.html', 0, 1, '2015-01-10 00:00:01', 'fa-user', '');
insert into sys_resource (id, parentid, name, type, "VALUE", show_state, show_mode, order_time, icon, descn)
values (3, 1, '角色管理', 'URL', '/manage/system/role/index.html', 0, 1, '2014-01-10 00:00:01', 'fa-user-circle-o', '');
insert into sys_resource (id, parentid, name, type, "VALUE", show_state, show_mode, order_time, icon, descn)
values (4, 1, '资源菜单', 'URL', '/manage/system/resource/index.html', 0, 1, '2014-01-10', 'fa-list', '');
INSERT INTO sys_resource (id, parentid, name, type, "VALUE", show_state, show_mode, order_time, icon, descn)
VALUES (5, 1, '机构管理', 'URL', '/manage/module/security/org/index.html', 0, 1, '2014-01-09 02:39:40', 'fa-sitemap', '');
insert into sys_resource (id, parentid, name, type, "VALUE", show_state, show_mode, order_time, icon, descn)
values (7, 1, '桌面管理', 'URL', '/manage/system/portallet/index.html', 0, 1, '2014-01-08 02:39:40', 'fa-dashboard', '');
insert into sys_resource (id, parentid, name, type, "VALUE", show_state, show_mode, order_time, icon, descn)
values (8, 1, '连接池监控', 'URL', '/manage/druid/index.html', 0, 2, '2014-01-08 02:39:40', 'fa-eye', '');
INSERT INTO sys_resource(id, name, type, show_state, order_time, "VALUE", show_mode, icon, descn)
VALUES (2019022201, '通用功能', 'MENU', 0, '2015-10-23 18:32:04', '', 1, 'fa-th', '');


insert into SYS_ROLE (id, name, descn)
values (1, 'ROLE_SYSTEM', '系统管理角色');

insert into sys_role_resc (role_id, resc_id)
values (1, 1);
insert into sys_role_resc (role_id, resc_id)
values (1, 2);
insert into sys_role_resc (role_id, resc_id)
values (1, 3);
insert into sys_role_resc (role_id, resc_id)
values (1, 4);
insert into sys_role_resc (role_id, resc_id)
values (1, 5);
insert into sys_role_resc (role_id, resc_id)
values (1, 7);
insert into sys_role_resc (role_id, resc_id)
values (1, 8);
insert into sys_role_resc (role_id, resc_id)
values (1, 2019022201);

INSERT INTO sys_user(id, username, real_name, pinyin, password, salt, user_type, email, mobile_no, org_id, org_name, last_modify_time, expiration_time, unlock_time, login_status, login_fail_times, login_time, status, descn, create_time, update_time)
VALUES (1, 'admin', '超级管理员', 'S', 'ab7cc1898fe24ef738595e56759b17893f2dbcc6', 'f10a5bda42097431', 1, 'zp820705@163.com', '13896177630', 1, 'acooly', '2019-02-21 18:10:23', NULL, NULL, 1, 0, NULL, 1, '', '2014-01-07 00:00:00', '2019-02-21 18:10:23');

insert into sys_user_role(role_id, user_id)
values (1, 1);

