<div style="padding: 5px;font-family:微软雅黑;">
    <table class="tableForm" width="100%">
        <tr>
            <th width="25%">用户名:</th>
            <td>${appCustomer.userName}</td>
        </tr>
        <tr>
            <th>访问码:</th>
            <td>${appCustomer.accessKey}</td>
        </tr>
        <tr>
            <th>安全码:</th>
            <td>${appCustomer.secretKey}</td>
        </tr>
        <tr>
            <th>设备类型:</th>
            <td>${appCustomer.deviceType}</td>
        </tr>
        <tr>
            <th>设备型号:</th>
            <td>${appCustomer.deviceModel}</td>
        </tr>
        <tr>
            <th>设备标识:</th>
            <td>${appCustomer.deviceId}</td>
        </tr>
        <tr>
            <th>创建时间:</th>
            <td>${appCustomer.createTime}</td>
        </tr>
        <tr>
            <th>更新时间:</th>
            <td>${appCustomer.updateTime}</td>
        </tr>
        <tr>
            <th>状态:</th>
            <td>${appCustomer.status}</td>
        </tr>
    </table>
</div>
